apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "svc.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
